export const TIMETABLE_FROM_LOCATION_LOADING = 'TIMETABLE_FROM_LOCATION_LOADING';
export const SET_TIMETABLE_FOR_LOCATION = 'SET_TIMETABLE_FOR_LOCATION';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_FAILED_AUTHENTICATION_ERROR = 'LOGIN_FAILED_AUTHENTICATION_ERROR';

export const SET_LOCATION_LIST = 'SET_LOCATION_LIST';

export const APP_FAILURE = 'APP_FAILURE';
export const BUSSTOP_ADDED_TO_LOCATION = 'BUSSTOP_ADDED_TO_LOCATION';