"""empty message

Revision ID: 9fc65282e9ee
Revises: 02
Create Date: 2019-11-24 23:17:11.093321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03'
down_revision = '02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_token')
    # ### end Alembic commands ###
